"""create users

Revision ID: 56eb0b13f8ca
Revises: 92f630e21c8b
Create Date: 2025-12-15 22:25:24.038458

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '56eb0b13f8ca'
down_revision: Union[str, Sequence[str], None] = '92f630e21c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
