"""create users

Revision ID: 763569c86a95
Revises: 
Create Date: 2025-12-15 22:17:09.107010

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '763569c86a95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
